### ISSUE TITLE
关于输入数据的问题

### ISSUE THREAD

**Issue by cosinehuang** [Aman-4-Real/See-or-Guess#3]
您好，非常感谢您的工作！我在复现代码的时候有一个问题，数据集中的反事实图像都是您手动定位进行处理的吗？是否可以提供您处理之后的数据集及相应位置坐标呢？

**Comment by Aman-4-Real** [comment]
你好，感谢对我们工作的关注。反事实图像的 bounding box 来自数据集中的标注，统一格式后整理成对应的数据形式，可以参考我们 README 中的细节。我上传了一份处理之后的数据放到 [data/](https://github.com/Aman-4-Real/See-or-Guess/tree/main/data) 中了，希望可以帮助你。

**Comment by cosinehuang** [comment]
非常感谢！


---- 回复的原邮件 ----
发件人  Qian ***@***.***> 日期  2024年11月11日 13:15 收件人  ***@***.***> 抄送至  ***@***.***>***@***.***> 主题  Re: [Aman-4-Real/See-or-Guess] 关于输入数据的问题 (Issue #3)  

你好，感谢对我们工作的关注。反事实图像的 bounding box 来自数据集中的标注，统一格式后整理成对应的数据形式，可以参考我们 README 中的细节。我上传了一份处理之后的数据放到 data/ 中了，希望可以帮助你。
