### ISSUE TITLE
代码细节问题

### ISSUE THREAD

**Issue by cosinehuang** [Aman-4-Real/See-or-Guess#4]
您好！我在复现您的代码时遇到了问题，在我设置 do_TE: True之后，在blip2_opt.py文件中第123行，samples中并没有'masked_images_list'、'gen_caps_list'、'masked_item_lens'、'entities_list'、'prefixes_list'这些关键字，它只包含了'image_list'、'id_list'、'ann_list'等。我在调试前面代码时也没找到问题所在，我想知道是我哪一步出了问题，希望得到您的指点！非常感谢！

**Comment by Aman-4-Real** [comment]
这些来自 [dataloader_utils.py](https://github.com/Aman-4-Real/See-or-Guess/blob/main/src/lavis/datasets/datasets/dataloader_utils.py#L167) 中的实现，在给出的数据里面是包含的。如果没有包含这些字段，可以根据 [cfr_caption_datasets.py](https://github.com/Aman-4-Real/See-or-Guess/blob/main/src/lavis/datasets/datasets/cfr_caption_datasets.py) 检查是否有正确初始化和导入数据。另外，gen_caps_list 需要使用原本的模型生成得到（实际上是对反事实caption的估计，论文中有讨论），这个也需要提前准备好。

**Comment by cosinehuang** [comment]
好的，明白啦，我再去试一试，谢谢！
