### ISSUE TITLE
模型参数加载错误

### ISSUE THREAD

**Issue by cosinehuang** [Aman-4-Real/See-or-Guess#5]
您好！我在加载模型时出现如下报错：
RuntimeError: Error(s) in loading state_dict for Blip2OPT:
        size mismatch for opt_proj.weight: copying a param with shape torch.Size([2560, 768]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for opt_proj.bias: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([768]).
我初步找了一下原因，我下载的blip2-opt-2.7b中hidden_size是2560，但是在模型初始化这里是768（self.opt_model.config.hidden_size），如果我强制把该值设置为2560，在后续的代码中也会报错：
    inputs_embeds = torch.cat([inputs_opt, inputs_embeds], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2560 but got size 768 for tensor number 1 in the list.
还有这一输出：2024-11-20 22:11:12,591 [INFO] [In blip2.py] There are 708 missing keys. Ignored.
是我模型下载错误吗，还是哪个环节出了问题，希望得到您的解答！

**Comment by Aman-4-Real** [comment]
blip2-opt-2.7b 中 Qformer 的 hidden_size 应该是 768，opt 的 hidden_size 是 2560，近期官方 hub 中对文件做了[更新](https://huggingface.co/Salesforce/blip2-opt-2.7b/tree/main)，我不确定目前是不是能完全兼容。附上我当时使用的 blip2-opt-2.7b 的 config 供你参考。第二个输出是我加的，你可以忽略它。

![image](https://github.com/user-attachments/assets/2aa3e43a-5230-4aac-a17d-4cbccbf12875)
[config.json](https://github.com/user-attachments/files/17896877/config.json)

**Comment by cosinehuang** [comment]
多谢！我也发现就是768对不上2560，我手动改了config中的参数，但是进行训练后测试时输出的句子很差，几乎全是the之类的单词。我再找找问题所在。


---- 回复的原邮件 ----
发件人  Qian ***@***.***> 日期  2024年11月25日 11:54 收件人  ***@***.***> 抄送至  ***@***.***>***@***.***> 主题  Re: [Aman-4-Real/See-or-Guess] 模型参数加载错误 (Issue #5)  

blip2-opt-2.7b 中 Qformer 的 hidden_size 应该是 768，opt 的 hidden_size 是 2560，近期官方 hub 中对文件做了更新，我不确定目前是不是能完全兼容。附上我当时使用的 blip2-opt-2.7b 的 config 供你参考。第二个输出是我加的，你可以忽略它。
image.png (view on web)
 config.json

**Comment by Aman-4-Real** [comment]
> 多谢！我也发现就是768对不上2560，我手动改了config中的参数，但是进行训练后测试时输出的句子很差，几乎全是the之类的单词。我再找找问题所在。
> […](#)
> ---- 回复的原邮件 ---- 发件人 Qian ***@***.***> 日期 2024年11月25日 11:54 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [Aman-4-Real/See-or-Guess] 模型参数加载错误 (Issue #5) blip2-opt-2.7b 中 Qformer 的 hidden_size 应该是 768，opt 的 hidden_size 是 2560，近期官方 hub 中对文件做了更新，我不确定目前是不是能完全兼容。附上我当时使用的 blip2-opt-2.7b 的 config 供你参考。第二个输出是我加的，你可以忽略它。 image.png (view on web) config.json — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

如果正则的 loss 权重比较大可能会出现这种情况。我的观察是模型对 alpha 参数比较敏感，建议配合数据集大致确定基本参数后小幅度地调整，或者配合 lr 调整试试。

**Comment by cosinehuang** [comment]
好的，我多试试。非常感谢！


---- 回复的原邮件 ----
发件人  Qian ***@***.***> 日期  2024年11月25日 13:15 收件人  ***@***.***> 抄送至  ***@***.***>***@***.***> 主题  Re: [Aman-4-Real/See-or-Guess] 模型参数加载错误 (Issue #5)  

多谢！我也发现就是768对不上2560，我手动改了config中的参数，但是进行训练后测试时输出的句子很差，几乎全是the之类的单词。我再找找问题所在。
 …
 ---- 回复的原邮件 ---- 发件人 Qian @.> 日期 2024年11月25日 11:54 收件人 @.> 抄送至 @.>@.> 主题 Re: [Aman-4-Real/See-or-Guess] 模型参数加载错误 (Issue #5) blip2-opt-2.7b 中 Qformer 的 hidden_size 应该是 768，opt 的 hidden_size 是 2560，近期官方 hub 中对文件做了更新，我不确定目前是不是能完全兼容。附上我当时使用的 blip2-opt-2.7b 的 config 供你参考。第二个输出是我加的，你可以忽略它。 image.png (view on web) config.json — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>
如果正则的 loss 权重比较大可能会出现这种情况。我的观察是模型对 alpha 参数比较敏感，建议配合数据集大致确定基本参数后小幅度地调整，或者配合 lr 调整试试。
